# This template demonstrates a DAG task level timeout.
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-task-level-timeout-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
        arguments:
          parameters: [{name: timeout, value: "30s"}]
      - name: B
        depends: "A"
        template: echo
        arguments:
          parameters: [{name: timeout, value: "10s"}]
      - name: C
        depends: "A"
        template: echo2
      - name: D
        timeout: "10s"
        depends: "A"
        template: echo3
      - name: E
        depends: "A"
        template: echo3

  - name: echo
    timeout: "{{inputs.parameters.timeout}}"
    inputs:
      parameters:
      - name: timeout
    container:
      image: docker.reg.me:6698/v3/debian:9.4
      command: [sleep, "15s"]

  - name: echo2
    timeout: "10s"
    container:
      image: docker.reg.me:6698/v3/debian:9.4
      command: [sleep, "15s"]

  - name: echo3
    container:
      image: docker.reg.me:6698/v3/debian:9.4
      command: [sleep, "15s"]

